spring.application.name=AuctionBazaar

# DataSource Configuration
spring.datasource.url=${Database_URI}
spring.datasource.username=${Db_username}
spring.datasource.password=${Db_password}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=${PORT:8080}

# Swagger / OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Spring Security
spring.security.user.name=admin@example.com
spring.security.user.password=admin
spring.security.user.roles=ADMIN